### PR TITLE
Update bots.json

### PR DESCRIPTION
**Pull request by kal-byte**
Updated my bot with it's latest information.

### CODE REVIEW

**Comment by nerrixDE** [comment]
@kal-byte  unfortunately we need to do the same thing again (make a new PR fixing this what you proposed here). Can you edit the original issue with your submission too? So we can avoid this in the future xd (yes, thats hacky, but new backend coming soon!)

**Comment by nerrixDE** [comment]
better change the issue itself

**Comment by kal-byte** [comment]
Uh... Okay?

**Comment by nerrixDE** [comment]
@kal-byte yeah, the initial issue

**Pull request merged**
